### ISSUE TITLE
Join us in fghting covid as an iPXE expert

### ISSUE THREAD

**Issue by sokoow** [forwardcomputers/pxe#1]
Hey,

Cool project, it ideally looks like you'd be able to help us with fighting COVID with it!

We're planning to use a lot of iPXE related things, and your expertise would be really useful for us.

Join us on: https://devpost.com/software/help-education-sector-to-produce-more-laptops-for-students

Greetings, Karol & the team.

**Comment by forwardcomputers** [comment]
Closed
